Repository devops-fall-2019-promotions-squad/promotions, pull requests merged in 2019-10, with the labels that each got.

#20 Create app skeleton
  .gitignore
  Vagrantfile
  service/__init__.py
  service/models.py
  service/service.py
Labels: enhancement

#25 Add list all promotions, query by promotion code feature
  .pylintrc
  requirements.txt
  service/models.py
  service/service.py
  tests/__init__.py
  tests/promotion_factory.py
  tests/test_promotion.py
  tests/test_service.py
Labels: enhancement

#31 Delete promotion
  service/service.py
  tests/test_promotion.py
  tests/test_service.py
Labels: enhancement

#34 Apply promotion on products
  service/models.py
  service/service.py
  tests/promotion_factory.py
  tests/test_promotion.py
  tests/test_service.py
Labels: enhancement

#37 add error handlers
  service/service.py
  tests/test_service.py
Labels: enhancement

#29 Add promotion
  service/models.py
  service/service.py
  tests/test_promotion.py
  tests/test_service.py
Labels: enhancement

#39 convert start_date and expiry_date to datetime objects
  service/models.py
  service/service.py
  tests/promotion_factory.py
  tests/test_promotion.py
  tests/test_service.py
Labels: bug

#41 Update promotion
  service/models.py
  service/service.py
  tests/test_service.py
Labels: enhancement

#42 Fix product field in Promotion
  service/models.py
  service/service.py
  tests/promotion_factory.py
  tests/test_promotion.py
  tests/test_service.py
Labels: enhancement

#43 Refine coding style
  .pylintrc
  service/models.py
  service/service.py
  tests/promotion_factory.py
  tests/test_promotion.py
  tests/test_service.py
Labels: technical debt
